Repository ISISComputingGroup/EPICS-isisdae, pull requests merged in 2022-01, with the labels that each got.

#73 Remove isisicpint/nodcom option
  isisdaeApp/src/Makefile
  isisdaeApp/src/dae.h
  isisdaeApp/src/dae_isisicpint_dummy.cpp
  isisdaeApp/src/lib/windows-x64-debug/isisicpint.lib
  isisdaeApp/src/lib/windows-x64/isisicpint.lib
  isisdaeTestApp/src/build.mak
  postbuild/update_dlls.bat
Labels: size/XL

#74 Add set icp value
  isisdaeApp/src/isisdaeInterface.cpp
  isisdaeApp/src/isisdaeInterface.h
  isisdaeApp/src/isisicp.tlh
  isisdaeApp/src/isisicp.tli
Labels: size/S

#57 Expose PVs for remote DAE register monitoring
  isisdaeApp/Db/isisdae.db
  isisdaeApp/src/isisdaeDriver.cpp
  isisdaeApp/src/isisdaeDriver.h
  isisdaeApp/src/isisdaeInterface.cpp
  isisdaeApp/src/isisdaeInterface.h
Labels: size/L

#75 Live channel autosize
  isisdaeApp/src/isisdaeDriver.cpp
Labels: size/M

#76 Add daetype
  isisdaeApp/Db/isisdae.db
  isisdaeApp/src/isisdaeDriver.cpp
  isisdaeApp/src/isisdaeDriver.h
Labels: size/M

#71 Ticket4608 Added test records
  isisdaeApp/Db/ADisisdae.template
Labels: size/S
